// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfqEApSnPi6KCnNxkVxja6kqcrNtbngdE',
    appId: '1:279487260741:web:8cc94296652cb025279b2c',
    messagingSenderId: '279487260741',
    projectId: 'brain-bounce',
    authDomain: 'brain-bounce.firebaseapp.com',
    storageBucket: 'brain-bounce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWKnK9qxjrsyqm5EMShjj75lg6bDhNzmU',
    appId: '1:279487260741:android:c5eafc10d575b645279b2c',
    messagingSenderId: '279487260741',
    projectId: 'brain-bounce',
    storageBucket: 'brain-bounce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEXljp0T0R64zOb0JMxLO50UXcSvi6BIw',
    appId: '1:279487260741:ios:4ea9dfac4b36e6f6279b2c',
    messagingSenderId: '279487260741',
    projectId: 'brain-bounce',
    storageBucket: 'brain-bounce.appspot.com',
    iosBundleId: 'com.example.brainBounce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEXljp0T0R64zOb0JMxLO50UXcSvi6BIw',
    appId: '1:279487260741:ios:fecf17ae0df1a22a279b2c',
    messagingSenderId: '279487260741',
    projectId: 'brain-bounce',
    storageBucket: 'brain-bounce.appspot.com',
    iosBundleId: 'com.example.brainBounce.RunnerTests',
  );
}
